const verbs = [
['be','was/were','been'],['bear','bore','born/borne'],['beat','beat','beaten'],['become','became','become'],['begin','began','begun'],['bend','bent','bent'],['bet','bet','bet'],['bid','bid','bid'],['bind','bound','bound'],['bite','bit','bitten'],['bleed','bled','bled'],['blow','blew','blown'],['break','broke','broken'],['breed','bred','bred'],['bring','brought','brought'],['broadcast','broadcast','broadcast'],['build','built','built'],['burst','burst','burst'],['buy','bought','bought'],['cast','cast','cast'],['catch','caught','caught'],['choose','chose','chosen'],['cling','clung','clung'],['come','came','come'],['cost','cost','cost'],['creep','crept','crept'],['cut','cut','cut'],['deal','dealt','dealt'],
['dig','dug','dug'],['dive','dove/dived','dove/dived'],['do','did','done'],['draw','drew','drawn'],['drink','drank','drunk'],['drive','drove','driven'],['eat','ate','eaten'],['fall','fell','fallen'],['feed','fed','fed'],['feel','felt','felt'],['fight','fought','fought'],['find','found','found'],['fit','fit','fit'],['flee','fled','fled'],['fly','flew','flown'],['forbid','forbade','forbidden'],['forget','forgot','forgotten'],['forgive','forgave','forgiven'],['freeze','froze','frozen'],['get','got','got/gotten'],['give','gave','given'],['go','went','gone'],['grind','ground','ground'],['grow','grew','grown'],['read','read','read'],['ride','rode','ridden'],['ring','rang','rung'],['rise','rose','risen'],
['hang','hung','hung'],['have','had','had'],['hear','heard','heard'],['hide','hid','hidden'],['hit','hit','hit'],['hold','held','held'],['hurt','hurt','hurt'],['keep','kept','kept'],['know','knew','known'],['lay','laid','laid'],['leave','left','left'],['light','lit/lighted','lit/lighted'],['lose','lost','lost'],['make','made','made'],['mean','meant','meant'],['meet','met','met'],['mistake','mistook','mistaken'],['overcome','overcame','overcome'],['overdo','overdid','overdone'],['overtake','overtook','overtaken'],['overthrow','overthrew','overthrown'],['pay','paid','paid'],['plead','pled/pleaded','pled/pleaded'],['prove','proved','proven/proved'],['put','put','put'],['quit','quit','quit'],
['run','ran','run'],['say','said','said'],['see','saw','seen'],['seek','sought','sought'],['sell','sold','sold'],['send','sent','sent'],['set','set','set'],['sew','sewed','sewn/sewed'],['shake','shook','shaken'],['shed','shed','shed'],['shine','shone/shined','shone/shined'],['shoot','shot','shot'],['show','showed','shown/showed'],['shrink','shrank/shrunk','shrunk/shrunken'],['shut','shut','shut'],['sing','sang','sung'],['sink','sank','sunk'],['sit','sat','sat'],['sleep','slept','slept'],['slide','slid','slid'],['slit','slit','slit'],['speak','spoke','spoken'],['speed','sped','sped'],['spend','spent','spent'],['spin','spun','spun'],['split','split/splat','split/splat'],
['spread','spread','spread'],['spring','sprang','sprung'],['stand','stood','stood'],['steal','stole','stolen'],['stick','stuck','stuck'],['sting','stung','stung'],['stink','stank','stunk'],['strike','struck','struck/stricken'],['strive','strove','striven'],['swear','swore','sworn'],['sweep','swept','swept'],['swell','swelled','swelled/swollen'],['swim','swam','swum'],['swing','swung','swung'],['take','took','taken'],['teach','taught','taught'],['tear','tore','torn'],['tell','told','told'],['think','thought','thought'],['throw','threw','thrown'],['understand','understood','understood'],['uphold','upheld','upheld'],['upset','upset','upset'],['wake','woke','woken'],['wear','wore','worn'],['weave','wove','woven'],['wed','wedded/wed','wedded/wed'],['weep','wept','wept'],['win','won','won'],['wind','wound','wound'],['withdraw','withdrew','withdrawn'],['withhold','withheld','withheld'],['withstand','withstood','withstood'],['wring','wrung','wrung'],['write','wrote','written'],['burn','burned/burnt','burned/burnt'],['dream','dreamed/dreamt','dreamed/dreamt'],['kneel','kneeled/knelt','kneeled/knelt'],['learn','learned/learnt','learned/learnt'],['leap','leaped/leapt','leaped/leapt'],['spill','spilled/spilt','spilled/spilt'],['spoil','spoiled/spoilt','spoiled/spoilt']
].map(([base,past,participle])=>({base,past,participle}));
const $ = s => document.querySelector(s); let accountUser=null, progress={}, queue=[], current=null, checked=false;
const normalize = value => value.trim().toLowerCase().replaceAll(/\s+/g,''); const choices = value => normalize(value).split('/');
function setMessage(text,type=''){const el=$('#authMessage');el.textContent=text;el.className=`message ${type}`.trim()}
function bytesToBase64Url(bytes){let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')};function base64UrlToBytes(value){const padded=value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4);return Uint8Array.from(atob(padded),char=>char.charCodeAt(0))};function newPasswordSalt(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);return bytesToBase64Url(bytes)};async function passwordProof(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:base64UrlToBytes(salt),iterations:210000},key,256);return bytesToBase64Url(new Uint8Array(bits))};async function readAuthResponse(response){if(!(response.headers.get('content-type')||'').includes('application/json'))throw new Error('账号服务暂时没有正常响应，请稍后再试。');return response.json()}
function updateAccountUI(){const inAccount=Boolean(accountUser);$('#authLoggedOut').classList.toggle('hidden',inAccount);$('#authLoggedIn').classList.toggle('hidden',!inAccount);$('#accountButton').textContent=inAccount?accountUser.username:'登录 / 注册';if(inAccount)$('#accountName').textContent=accountUser.username}
function openAuth(){ $('#authPanel').classList.remove('hidden'); updateAccountUI(); if(!accountUser) $('#usernameInput').focus(); } function closeAuth(){$('#authPanel').classList.add('hidden')}
async function authPayload(action,username,password){if(action==='register'){const salt=newPasswordSalt();return {passwordProof:await passwordProof(password,salt),passwordSalt:salt}}const response=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'challenge',username})}),data=await readAuthResponse(response);if(!response.ok)throw new Error(data.error||'账号或密码不正确。');return data.scheme==='client-v1'?{passwordProof:await passwordProof(password,data.salt)}:{password}}
async function submitAuth(action){const username=$('#usernameInput').value.trim(),password=$('#passwordInput').value;if(!username||!password){setMessage('请先填写账号和密码。','error');return}setMessage(action==='register'?'正在安全创建账号…':'正在安全登录…');try{const credentials=await authPayload(action,username,password),response=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,username,...credentials})}),data=await readAuthResponse(response);if(!response.ok)throw new Error(data.error||'操作未完成。');accountUser=data.user;$('#passwordInput').value='';updateAccountUI();setMessage('登录成功，复习安排已同步。','success');await loadProgress();closeAuth()}catch(error){setMessage(error.message||'操作未完成，请稍后再试。','error')}}
async function loadAuth(){try{const response=await fetch('/api/auth'),data=await readAuthResponse(response);accountUser=data.user||null;updateAccountUI();if(accountUser)await loadProgress();else renderStats()}catch{accountUser=null;updateAccountUI();renderStats()}}
async function loadProgress(){try{const response=await fetch('/api/progress'),data=await response.json();if(!response.ok)throw new Error(data.error);progress=Object.fromEntries(data.cards.map(item=>[item.verb,item]));renderStats()}catch{progress={};renderStats()}}
function renderStats(){const now=Date.now(),done=Object.values(progress).filter(p=>p.repetitions>=2).length,due=verbs.filter(v=>!progress[v.base]||Date.parse(progress[v.base].dueAt)<=now).length;$('#dueCount').textContent=accountUser?due:'—';$('#learnedCount').textContent=accountUser?done:'—';$('#totalCount').textContent=verbs.length}
function buildQueue(){const now=Date.now(),due=verbs.filter(v=>!progress[v.base]||Date.parse(progress[v.base].dueAt)<=now);return due.sort((a,b)=>(progress[a.base]?.repetitions||0)-(progress[b.base]?.repetitions||0))}
function startStudy(){if(!accountUser){openAuth();setMessage('请先登录，才能把复习安排保存到你的账号。');return}queue=buildQueue();$('#welcomePanel').classList.add('hidden');$('#dashboard').classList.add('hidden');$('.how').classList.add('hidden');$('#studyPanel').classList.remove('hidden');showNext()}
function showNext(){checked=false;$('#answerReveal').classList.add('hidden');$('#completeState').classList.add('hidden');$('#card').classList.remove('hidden');current=queue.shift();if(!current){$('#card').classList.add('hidden');$('#completeState').classList.remove('hidden');renderStats();return}const type=Math.random()<.5?'past':'participle';current.type=type;$('#questionLabel').textContent=type==='past'?'写出过去式':'写出过去分词';$('#baseWord').textContent=current.base;$('#promptText').textContent=`请写出 ${current.base} 的${type==='past'?'过去式':'过去分词'}`;$('#answerInput').value='';$('#answerInput').disabled=false;$('#answerInput').focus();$('#studyCount').textContent=`剩余 ${queue.length+1} 张`}
function checkAnswer(event){event.preventDefault();if(checked||!current)return;const answer=normalize($('#answerInput').value);if(!answer){$('#answerInput').focus();return}checked=true;const correct=choices(current[current.type]).includes(answer);$('#resultText').textContent=correct?'回答正确！选择这张卡的真实难度：':'没关系，正确变化如下：';$('#resultText').className=correct?'right':'wrong';$('#revealBase').textContent=current.base;$('#revealPast').textContent=current.past;$('#revealParticiple').textContent=current.participle;$('#answerInput').disabled=true;$('#answerReveal').classList.remove('hidden')}
async function rateCard(rating){if(!current)return;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=true);try{const response=await fetch('/api/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({verb:current.base,rating})}),data=await response.json();if(!response.ok)throw new Error(data.error);progress[current.base]=data.card;showNext()}catch(error){alert(error.message||'保存失败，请稍后再试。')}finally{document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=false)}}
function leaveStudy(){$('#studyPanel').classList.add('hidden');$('#welcomePanel').classList.remove('hidden');$('#dashboard').classList.remove('hidden');$('.how').classList.remove('hidden');renderStats()}
$('#accountButton').addEventListener('click',openAuth);$('#closeAuthButton').addEventListener('click',closeAuth);$('#authForm').addEventListener('submit',e=>{e.preventDefault();submitAuth('login')});$('#registerButton').addEventListener('click',()=>submitAuth('register'));$('#logoutButton').addEventListener('click',async()=>{await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'logout'})});accountUser=null;progress={};updateAccountUI();renderStats()});$('#startButton').addEventListener('click',startStudy);$('#answerForm').addEventListener('submit',checkAnswer);document.querySelectorAll('[data-rating]').forEach(button=>button.addEventListener('click',()=>rateCard(button.dataset.rating)));$('#backButton').addEventListener('click',leaveStudy);$('#completeBackButton').addEventListener('click',leaveStudy);loadAuth();
