name = "verb"
compatibility_date = "2026-08-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "maths-practice-history"
database_id = "30d08825-9dab-42ea-b37a-e4add3715c12"
